### ISSUE TITLE
登陆时未响应

### ISSUE THREAD

**Issue by NotKiri123** [FPSMasterTeam/FPSMaster#26]
在登陆[FPSMaster](https://github.com/FPSMasterTeam/FPSMaster-v3)的过程中，显示未响应。之后显示响应时间过长。手动关闭后出现了错误报告
[错误报告-2024-7-5_10.23.52.zip](https://github.com/user-attachments/files/16104305/-2024-7-5_10.23.52.zip)

**Comment by SuperSkidder** [comment]
这是由于Cloudflare CDN导致的。境内部分地区可能会无法访问我们的网站。很遗憾我们暂时无法解决，请自行使用网络代理工具。

**Comment by NotKiri123** [comment]
ok
