### ISSUE TITLE
最新版的客户端运动模糊出现问题

### ISSUE THREAD

**Issue by llllluo-lol** [FPSMasterTeam/FPSMaster#29]
最新版的客户端，在视觉功能中，运动模糊出现问题，按了之后整个客户端白屏

https://github.com/FPSMasterTeam/FPSMaster/assets/174916029/d9ae9743-0f0c-4aad-a5e9-748e1ed1ab22

**Comment by SuperSkidder** [comment]
检查模组兼容性
无法复现
