### ISSUE TITLE
崩溃报告2024.7.8已重新上传

### ISSUE THREAD

**Issue by hvhllllll** [FPSMasterTeam/FPSMaster#30]
玩着突然花屏然后结束进程后的报告
报告如下：
[错误报告-2024-7-8_16.53.51.zip](https://github.com/user-attachments/files/16135400/-2024-7-8_16.53.51.zip)

**Comment by SuperSkidder** [comment]
你没传上来

**Comment by hvhllllll** [comment]
已重新上传

**Comment by SuperSkidder** [comment]
暂时无法定位问题，疑似与客户端无关
