### ISSUE TITLE
Compat problem with PolyPatcher in 1.8.9 -   1.8.9版本与PolyPatcher存在兼容性问题

### ISSUE THREAD

**Issue by FsaxZ** [FPSMasterTeam/FPSMaster#41]
The game crashes when loading both FPSMaster(_1.8.9-v3.2.9_) and **PolyPatcher**. (I've not tested Patcher Mod yet.)   
在同时加载本Mod(_1.8.9-v3.2.9_)和 **PolyPatcher**  Mod时发生崩溃。（并未测试原Patcher Mod）。    

崩溃日志（CrashReports）：
[crash-2024-07-19_17.57.35-client.txt](https://github.com/user-attachments/files/16313868/crash-2024-07-19_17.57.35-client.txt)

**Comment by FsaxZ** [comment]
I've found a way to fix reluctantly, but it caused too much performence(FPS) lost to PolyPatcher.  
我找到了勉强修复这个问题的方案，但是会导致PolyPatcher 的优化功能(FPS)大幅受限  

top.fpsmaster.forge.mixin.MixinRenderManager:
```

@Mixin(value = RenderManager.class, priority = 999)  // 略降低这个类的注入优先级以允许PolyPatcher注入 - Lower the prority of this class to allow PolyPatcher to inject its mixin.
@Implements(@Interface(iface = IRenderManager.class, prefix = "fpsmaster$"))
public class MixinRenderManager implements IRenderManager {
……
}

```

**Comment by SuperSkidder** [comment]
近期会尝试解决。
