### ISSUE TITLE
开发时遇到问题

### ISSUE THREAD

**Issue by Sourcefuture** [FPSMasterTeam/FPSMaster#43]
我按照视频 BV1wM4m1U7n2 中的教程尝试构建项目 遇到了问题

> Task :generateGitProperties FAILED
Caught exception during close(): groovy.lang.MissingPropertyException: No such property: out for class: com.gorylenko.writer.NormalizeEOLOutputStream

Execution failed for task ':generateGitProperties'.
> No such property: out for class: com.gorylenko.writer.NormalizeEOLOutputStream

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date

尝试结局无果

请问如何解决
致谢

**Comment by FsaxZ** [comment]
同遇到过该问题，但自己当时是因为不是Git clone下来的而是下的源码zip,clone 的下来的就没问题，应该是Git没配置

**Comment by Sourcefuture** [comment]
我使用的是git clone 拉取的源码 问题仍没有解决 请求帮助
