### ISSUE TITLE
[bug/问题] 使用音乐时出现错误！

### ISSUE THREAD

**Issue by Vape1337** [FPSMasterTeam/FPSMaster#45]
在使用FPSM时使用他的音乐播放器，出现**`掉帧卡顿`**，我发现他没有`按照单曲循环`，`他在一直切换音乐`

**Comment by Vape1337** [comment]
![image](https://github.com/user-attachments/assets/28d51ec2-00dc-4e71-9c88-57743ac61fb2)
报毒了，在我的电脑无法允许

**Comment by Kizure1337** [comment]
你说得对，但是ranlib generates an index to the contents of an archive and stores it in the archive. The index lists each symbol defined by a member of an archive that is a relocatable object file.

You may use nm -s or nm --print-armap to list this index.

An archive with such an index speeds up linking to the library and allows routines in the library to call each other without regard to their placement in the archive.

The GNU ranlib program is another form of GNU ar; running ranlib is completely equivalent to executing ar -s.

**Comment by llllluo-lol** [comment]
哥们，你用的是什么杀毒啊？XD

**Comment by SuperSkidder** [comment]
此文件并非FPSMaster释放，请自行排查
