### ISSUE TITLE
图形用户界面主菜单和GUI自定义

### ISSUE THREAD

**Issue by XuYifanXXX** [FPSMasterTeam/FPSMaster#49]
图形用户界面主菜单背景属实太丑了，建议添加自定义选项，改成自己喜欢的图片，GUI的单纯色也不好看，整个半透明或者自定义图片替换（色盘）也可以。

**Comment by SuperSkidder** [comment]
主界面图片自定义已经有了 最新构建版本，在配置文件夹放 background.png 即可

**Comment by SuperSkidder** [comment]
gui 自定义暂时没空搞
